services:
  redis:
    image: redis:7.0.1
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Only run this when you're running for the first time
  # Otherwise, we don't need to run it always. Just used for data migration.
  # data-migration:
  #   build:
  #     context: .
  #     dockerfile: prisma.Dockerfile
  #   stop_grace_period: 0s
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./prisma/:/app/
  #   environment:
  #     - DATABASE_URL=postgresql://root:root@postgres:5432/postgres

  localstack:
    image: localstack/localstack:4.10.0
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./localstack-s3-setup.sh:/etc/localstack/init/ready.d/script.sh
      - "/var/run/docker.sock:/var/run/docker.sock"

  chainlit-ui:
    platform: linux/arm64
    depends_on:
      - redis
      - postgres
      - localstack
    build:
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - azure-openai.env
      - chainlit.env
    environment:
      AWS_COST_EXPLORER_MCP_HOST: 127.0.0.1
      AWS_COST_EXPLORER_MCP_BIND_HOST: 127.0.0.1
      AWS_COST_EXPLORER_MCP_CLIENT_HOST: 127.0.0.1
      AWS_COST_EXPLORER_MCP_URL: http://127.0.0.1:8001/mcp
      AWS_CCAPI_MCP_HOST: 127.0.0.1
      AWS_CCAPI_MCP_BIND_HOST: 127.0.0.1
      AWS_CCAPI_MCP_CLIENT_HOST: 127.0.0.1
      AWS_CCAPI_MCP_URL: http://127.0.0.1:8002/mcp
    volumes:
      - ./chainlit-config.toml:/app/.chainlit/config.toml
      - ./aws-rf-billingpoc-user.env:/app/aws.env

volumes:
  redis-data:
  postgres-data:
